MASTER_AREAS = [
    # North-West Pune (12 areas)
    {"id": 1, "name": "Hinjewadi Phase 1", "region": "North-West Pune", "latitude": 18.5882, "longitude": 73.7374, "density": 120, "area_type": "IT Hub", "urban_growth": "High", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 2, "name": "Hinjewadi Phase 2", "region": "North-West Pune", "latitude": 18.5905, "longitude": 73.7020, "density": 110, "area_type": "IT Hub", "urban_growth": "High", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 3, "name": "Hinjewadi Phase 3", "region": "North-West Pune", "latitude": 18.5802, "longitude": 73.6820, "density": 100, "area_type": "IT Hub", "urban_growth": "High", "green_space": "Medium", "population_density": "Medium", "development_stage": "Rapidly Expanding"},
    {"id": 4, "name": "Marunji", "region": "North-West Pune", "latitude": 18.6015, "longitude": 73.7190, "density": 80, "area_type": "Residential", "urban_growth": "High", "green_space": "Medium", "population_density": "Medium", "development_stage": "Rapidly Expanding"},
    {"id": 5, "name": "Wakad", "region": "North-West Pune", "latitude": 18.5987, "longitude": 73.7710, "density": 150, "area_type": "Residential", "urban_growth": "High", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 6, "name": "Tathawade", "region": "North-West Pune", "latitude": 18.6145, "longitude": 73.7540, "density": 130, "area_type": "Educational", "urban_growth": "High", "green_space": "Medium", "population_density": "Medium", "development_stage": "Rapidly Expanding"},
    {"id": 7, "name": "Punawale", "region": "North-West Pune", "latitude": 18.6300, "longitude": 73.7430, "density": 110, "area_type": "Residential", "urban_growth": "High", "green_space": "Medium", "population_density": "Medium", "development_stage": "Rapidly Expanding"},
    {"id": 8, "name": "Ravet", "region": "North-West Pune", "latitude": 18.6441, "longitude": 73.7315, "density": 120, "area_type": "Residential", "urban_growth": "Medium", "green_space": "Medium", "population_density": "Medium", "development_stage": "Established"},
    {"id": 9, "name": "Baner", "region": "North-West Pune", "latitude": 18.5590, "longitude": 73.7788, "density": 140, "area_type": "Commercial", "urban_growth": "High", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 10, "name": "Balewadi", "region": "North-West Pune", "latitude": 18.5760, "longitude": 73.7730, "density": 130, "area_type": "Mixed Use", "urban_growth": "High", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 11, "name": "Pashan", "region": "North-West Pune", "latitude": 18.5385, "longitude": 73.7942, "density": 90, "area_type": "Residential", "urban_growth": "Low", "green_space": "High", "population_density": "Medium", "development_stage": "Established"},
    {"id": 12, "name": "Bavdhan", "region": "North-West Pune", "latitude": 18.5144, "longitude": 73.7758, "density": 100, "area_type": "Residential", "urban_growth": "Medium", "green_space": "High", "population_density": "Medium", "development_stage": "Established"},

    # North Pune (13 areas)
    {"id": 13, "name": "Bhosari", "region": "North Pune", "latitude": 18.6231, "longitude": 73.8439, "density": 160, "area_type": "Industrial", "urban_growth": "Low", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 14, "name": "Moshi", "region": "North Pune", "latitude": 18.6830, "longitude": 73.8490, "density": 90, "area_type": "Mixed Use", "urban_growth": "High", "green_space": "Medium", "population_density": "Medium", "development_stage": "Rapidly Expanding"},
    {"id": 15, "name": "Chikhali", "region": "North Pune", "latitude": 18.6720, "longitude": 73.8110, "density": 110, "area_type": "Industrial", "urban_growth": "High", "green_space": "Low", "population_density": "High", "development_stage": "Rapidly Expanding"},
    {"id": 16, "name": "Talawade", "region": "North Pune", "latitude": 18.6860, "longitude": 73.7890, "density": 80, "area_type": "IT Hub", "urban_growth": "Medium", "green_space": "Medium", "population_density": "Medium", "development_stage": "Established"},
    {"id": 17, "name": "Nigdi", "region": "North Pune", "latitude": 18.6500, "longitude": 73.7740, "density": 120, "area_type": "Residential", "urban_growth": "Low", "green_space": "High", "population_density": "High", "development_stage": "Established"},
    {"id": 18, "name": "Pradhikaran", "region": "North Pune", "latitude": 18.6470, "longitude": 73.7660, "density": 100, "area_type": "Residential", "urban_growth": "Low", "green_space": "High", "population_density": "Medium", "development_stage": "Established"},
    {"id": 19, "name": "Akurdi", "region": "North Pune", "latitude": 18.6455, "longitude": 73.7915, "density": 130, "area_type": "Educational", "urban_growth": "Low", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},
    {"id": 20, "name": "Chinchwad", "region": "North Pune", "latitude": 18.6311, "longitude": 73.7850, "density": 170, "area_type": "Industrial", "urban_growth": "Low", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 21, "name": "Pimpri", "region": "North Pune", "latitude": 18.6277, "longitude": 73.8122, "density": 180, "area_type": "Commercial", "urban_growth": "Low", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 22, "name": "Pimple Saudagar", "region": "North Pune", "latitude": 18.5982, "longitude": 73.8005, "density": 140, "area_type": "Residential", "urban_growth": "High", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 23, "name": "Pimple Gurav", "region": "North Pune", "latitude": 18.5830, "longitude": 73.8210, "density": 130, "area_type": "Residential", "urban_growth": "Medium", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 24, "name": "Dapodi", "region": "North Pune", "latitude": 18.5772, "longitude": 73.8341, "density": 150, "area_type": "Mixed Use", "urban_growth": "Low", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 25, "name": "PCMC", "region": "North Pune", "latitude": 18.6298, "longitude": 73.7997, "density": 160, "area_type": "Mixed Use", "urban_growth": "Low", "green_space": "Low", "population_density": "High", "development_stage": "Established"},

    # North-East Pune (10 areas)
    {"id": 26, "name": "Viman Nagar", "region": "North-East Pune", "latitude": 18.5679, "longitude": 73.9143, "density": 160, "area_type": "Mixed Use", "urban_growth": "High", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 27, "name": "Kalyani Nagar", "region": "North-East Pune", "latitude": 18.5463, "longitude": 73.9033, "density": 150, "area_type": "Commercial", "urban_growth": "Low", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},
    {"id": 28, "name": "Yerwada", "region": "North-East Pune", "latitude": 18.5529, "longitude": 73.8796, "density": 190, "area_type": "Commercial", "urban_growth": "Low", "green_space": "Low", "population_density": "High", "development_stage": "Undergoing Renewal"},
    {"id": 29, "name": "Lohegaon", "region": "North-East Pune", "latitude": 18.6012, "longitude": 73.9268, "density": 80, "area_type": "Residential", "urban_growth": "High", "green_space": "Medium", "population_density": "Medium", "development_stage": "Rapidly Expanding"},
    {"id": 30, "name": "Dhanori", "region": "North-East Pune", "latitude": 18.5900, "longitude": 73.8966, "density": 100, "area_type": "Residential", "urban_growth": "High", "green_space": "Medium", "population_density": "Medium", "development_stage": "Rapidly Expanding"},
    {"id": 31, "name": "Vishrantwadi", "region": "North-East Pune", "latitude": 18.5714, "longitude": 73.8789, "density": 130, "area_type": "Residential", "urban_growth": "Medium", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 32, "name": "Tingre Nagar", "region": "North-East Pune", "latitude": 18.5794, "longitude": 73.8910, "density": 110, "area_type": "Residential", "urban_growth": "Medium", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},
    {"id": 33, "name": "Kharadi", "region": "North-East Pune", "latitude": 18.5515, "longitude": 73.9475, "density": 180, "area_type": "IT Hub", "urban_growth": "High", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 34, "name": "Wagholi", "region": "North-East Pune", "latitude": 18.5795, "longitude": 73.9849, "density": 120, "area_type": "Mixed Use", "urban_growth": "High", "green_space": "Low", "population_density": "High", "development_stage": "Rapidly Expanding"},
    {"id": 35, "name": "Chandan Nagar", "region": "North-East Pune", "latitude": 18.5604, "longitude": 73.9392, "density": 140, "area_type": "Residential", "urban_growth": "Medium", "green_space": "Low", "population_density": "High", "development_stage": "Established"},

    # East Pune (7 areas)
    {"id": 36, "name": "Hadapsar", "region": "East Pune", "latitude": 18.5089, "longitude": 73.9260, "density": 170, "area_type": "Industrial", "urban_growth": "High", "green_space": "Low", "population_density": "High", "development_stage": "Undergoing Renewal"},
    {"id": 37, "name": "Magarpatta", "region": "East Pune", "latitude": 18.5134, "longitude": 73.9318, "density": 160, "area_type": "IT Hub", "urban_growth": "Low", "green_space": "High", "population_density": "High", "development_stage": "Established"},
    {"id": 38, "name": "Mundhwa", "region": "East Pune", "latitude": 18.5362, "longitude": 73.9304, "density": 130, "area_type": "Mixed Use", "urban_growth": "High", "green_space": "Low", "population_density": "High", "development_stage": "Rapidly Expanding"},
    {"id": 39, "name": "Fatima Nagar", "region": "East Pune", "latitude": 18.5065, "longitude": 73.8985, "density": 150, "area_type": "Residential", "urban_growth": "Low", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},
    {"id": 40, "name": "Wanowrie", "region": "East Pune", "latitude": 18.4988, "longitude": 73.8980, "density": 140, "area_type": "Residential", "urban_growth": "Low", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},
    {"id": 41, "name": "Camp (MG Road)", "region": "East Pune", "latitude": 18.5132, "longitude": 73.8780, "density": 180, "area_type": "Commercial", "urban_growth": "Low", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},
    {"id": 42, "name": "Koregaon Park", "region": "East Pune", "latitude": 18.5362, "longitude": 73.8940, "density": 130, "area_type": "Residential", "urban_growth": "Low", "green_space": "High", "population_density": "Medium", "development_stage": "Established"},

    # South-East Pune (6 areas)
    {"id": 43, "name": "Manjri", "region": "South-East Pune", "latitude": 18.5204, "longitude": 73.9535, "density": 90, "area_type": "Mixed Use", "urban_growth": "High", "green_space": "Medium", "population_density": "Medium", "development_stage": "Rapidly Expanding"},
    {"id": 44, "name": "Shewalewadi", "region": "South-East Pune", "latitude": 18.5020, "longitude": 73.9710, "density": 80, "area_type": "Residential", "urban_growth": "High", "green_space": "Medium", "population_density": "Low", "development_stage": "Rapidly Expanding"},
    {"id": 45, "name": "Undri", "region": "South-East Pune", "latitude": 18.4580, "longitude": 73.9030, "density": 100, "area_type": "Residential", "urban_growth": "High", "green_space": "High", "population_density": "Medium", "development_stage": "Rapidly Expanding"},
    {"id": 46, "name": "Pisoli", "region": "South-East Pune", "latitude": 18.4480, "longitude": 73.9010, "density": 85, "area_type": "Residential", "urban_growth": "High", "green_space": "High", "population_density": "Low", "development_stage": "Rapidly Expanding"},
    {"id": 47, "name": "Handewadi", "region": "South-East Pune", "latitude": 18.4660, "longitude": 73.9240, "density": 95, "area_type": "Residential", "urban_growth": "High", "green_space": "Medium", "population_density": "Medium", "development_stage": "Rapidly Expanding"},
    {"id": 48, "name": "Mohammadwadi", "region": "South-East Pune", "latitude": 18.4780, "longitude": 73.9160, "density": 110, "area_type": "Residential", "urban_growth": "Medium", "green_space": "Medium", "population_density": "Medium", "development_stage": "Established"},

    # South Pune (7 areas)
    {"id": 49, "name": "Katraj", "region": "South Pune", "latitude": 18.4529, "longitude": 73.8549, "density": 120, "area_type": "Educational", "urban_growth": "Medium", "green_space": "High", "population_density": "High", "development_stage": "Established"},
    {"id": 50, "name": "Kondhwa", "region": "South Pune", "latitude": 18.4770, "longitude": 73.8906, "density": 160, "area_type": "Mixed Use", "urban_growth": "High", "green_space": "Low", "population_density": "High", "development_stage": "Rapidly Expanding"},
    {"id": 51, "name": "Bibwewadi", "region": "South Pune", "latitude": 18.4788, "longitude": 73.8686, "density": 150, "area_type": "Residential", "urban_growth": "Low", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},
    {"id": 52, "name": "Dhankawadi", "region": "South Pune", "latitude": 18.4688, "longitude": 73.8504, "density": 140, "area_type": "Residential", "urban_growth": "Low", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},
    {"id": 53, "name": "Sahakar Nagar", "region": "South Pune", "latitude": 18.4920, "longitude": 73.8465, "density": 110, "area_type": "Residential", "urban_growth": "Low", "green_space": "High", "population_density": "Medium", "development_stage": "Established"},
    {"id": 54, "name": "Market Yard", "region": "South Pune", "latitude": 18.4890, "longitude": 73.8670, "density": 150, "area_type": "Commercial", "urban_growth": "Low", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 55, "name": "Gultekdi", "region": "South Pune", "latitude": 18.4975, "longitude": 73.8660, "density": 140, "area_type": "Mixed Use", "urban_growth": "Low", "green_space": "Low", "population_density": "High", "development_stage": "Established"},

    # South-West Pune (6 areas)
    {"id": 56, "name": "Ambegaon", "region": "South-West Pune", "latitude": 18.4542, "longitude": 73.8344, "density": 100, "area_type": "Educational", "urban_growth": "High", "green_space": "Medium", "population_density": "High", "development_stage": "Rapidly Expanding"},
    {"id": 57, "name": "Narhe", "region": "South-West Pune", "latitude": 18.4485, "longitude": 73.8236, "density": 120, "area_type": "Mixed Use", "urban_growth": "High", "green_space": "Low", "population_density": "High", "development_stage": "Rapidly Expanding"},
    {"id": 58, "name": "Dhayari", "region": "South-West Pune", "latitude": 18.4428, "longitude": 73.8075, "density": 110, "area_type": "Residential", "urban_growth": "High", "green_space": "Medium", "population_density": "High", "development_stage": "Rapidly Expanding"},
    {"id": 59, "name": "Nanded City", "region": "South-West Pune", "latitude": 18.4585, "longitude": 73.7942, "density": 90, "area_type": "Residential", "urban_growth": "Low", "green_space": "High", "population_density": "Medium", "development_stage": "Established"},
    {"id": 60, "name": "Sinhagad Road", "region": "South-West Pune", "latitude": 18.4725, "longitude": 73.8155, "density": 140, "area_type": "Commercial", "urban_growth": "Medium", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 61, "name": "Anand Nagar", "region": "South-West Pune", "latitude": 18.4844, "longitude": 73.8198, "density": 130, "area_type": "Residential", "urban_growth": "Medium", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},

    # West Pune (5 areas)
    {"id": 62, "name": "Kothrud", "region": "West Pune", "latitude": 18.5074, "longitude": 73.8077, "density": 160, "area_type": "Residential", "urban_growth": "Low", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},
    {"id": 63, "name": "Karve Nagar", "region": "West Pune", "latitude": 18.4905, "longitude": 73.8166, "density": 140, "area_type": "Educational", "urban_growth": "Low", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},
    {"id": 64, "name": "Warje", "region": "West Pune", "latitude": 18.4812, "longitude": 73.7997, "density": 120, "area_type": "Residential", "urban_growth": "Medium", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},
    {"id": 65, "name": "Erandwane", "region": "West Pune", "latitude": 18.5110, "longitude": 73.8290, "density": 150, "area_type": "Mixed Use", "urban_growth": "Low", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},
    {"id": 66, "name": "Deccan", "region": "West Pune", "latitude": 18.5173, "longitude": 73.8402, "density": 160, "area_type": "Commercial", "urban_growth": "Low", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},

    # Central Pune (8 areas)
    {"id": 67, "name": "Shivaji Nagar", "region": "Central Pune", "latitude": 18.5308, "longitude": 73.8474, "density": 170, "area_type": "Educational", "urban_growth": "Low", "green_space": "High", "population_density": "High", "development_stage": "Established"},
    {"id": 68, "name": "FC Road", "region": "Central Pune", "latitude": 18.5255, "longitude": 73.8413, "density": 180, "area_type": "Commercial", "urban_growth": "Low", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},
    {"id": 69, "name": "JM Road", "region": "Central Pune", "latitude": 18.5236, "longitude": 73.8441, "density": 180, "area_type": "Commercial", "urban_growth": "Low", "green_space": "Medium", "population_density": "High", "development_stage": "Established"},
    {"id": 70, "name": "Sadashiv Peth", "region": "Central Pune", "latitude": 18.5135, "longitude": 73.8465, "density": 190, "area_type": "Residential", "urban_growth": "Low", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 71, "name": "Narayan Peth", "region": "Central Pune", "latitude": 18.5178, "longitude": 73.8480, "density": 190, "area_type": "Residential", "urban_growth": "Low", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 72, "name": "Shaniwar Peth", "region": "Central Pune", "latitude": 18.5212, "longitude": 73.8504, "density": 190, "area_type": "Residential", "urban_growth": "Low", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
    {"id": 73, "name": "Kasba Peth", "region": "Central Pune", "latitude": 18.5230, "longitude": 73.8567, "density": 200, "area_type": "Residential", "urban_growth": "Low", "green_space": "Low", "population_density": "High", "development_stage": "Undergoing Renewal"},
    {"id": 74, "name": "Swargate", "region": "Central Pune", "latitude": 18.5018, "longitude": 73.8636, "density": 190, "area_type": "Commercial", "urban_growth": "Low", "green_space": "Low", "population_density": "High", "development_stage": "Established"},
]
