# Generated by Django 6.0.3 on 2026-06-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0004_systemmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_selected', models.BooleanField(default=True)),
            ],
        ),
    ]
