# Generated by Django 6.0.3 on 2026-06-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0005_selectedarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMonthlyAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('avg_temperature', models.FloatField()),
                ('avg_humidity', models.FloatField(blank=True, null=True)),
                ('data_source', models.CharField(default='open_meteo', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
