# Generated by Django 6.0.3 on 2026-06-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0006_historicalmonthlyaverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_mode', models.CharField(default='ai_enhanced', max_length=50)),
                ('provider', models.CharField(default='gemini', max_length=50)),
                ('model_name', models.CharField(default='gemini-2.5-flash', max_length=50)),
                ('last_successful_analysis', models.DateTimeField(blank=True, null=True)),
                ('pdf_report_type', models.CharField(default='full', max_length=50)),
                ('include_executive_summary', models.BooleanField(default=True)),
                ('include_rankings', models.BooleanField(default=True)),
                ('include_area_details', models.BooleanField(default=True)),
                ('include_recommendations', models.BooleanField(default=True)),
                ('include_appendix', models.BooleanField(default=True)),
                ('last_pdf_generated', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
