# Generated by Django 6.0.3 on 2026-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0007_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='provider_status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
