# Generated by Django 6.0.3 on 2026-06-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0008_systemsettings_cooldown_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='consecutive_failures',
            field=models.IntegerField(default=0),
        ),
    ]
