from ..types import AreaContext


def generate_root_causes(ctx: AreaContext, scores: dict) -> list[dict[str, str]]:
    causes: list[dict[str, str]] = []

    if ctx.building_density >= 140:
        causes.append({
            "cause": "High Building Density",
            "severity": "Critical",
            "detail": (
                f"A high density index of {ctx.building_density:.0f} in this {ctx.area_type.lower()} area indicates "
                "intensely concentrated urban development that maximizes surface heat retention and significantly "
                "reduces nighttime cooling."
            ),
        })
    elif ctx.building_density >= 100:
        causes.append({
            "cause": "Moderate Building Density",
            "severity": "Moderate",
            "detail": (
                f"Density index of {ctx.building_density:.0f} contributes to localized "
                f"heat accumulation, typical of a {ctx.development_stage.lower()} built environment."
            ),
        })

    if ctx.vegetation_index < 0.45:
        causes.append({
            "cause": "Severe Vegetation Deficit",
            "severity": "High",
            "detail": (
                f"The vegetation index of {ctx.vegetation_index:.2f} is dangerously below the optimal range. "
                f"Given the {ctx.urban_growth.lower()} growth rate, the lack of natural cooling and evapotranspiration "
                "is a primary driver of the heat island effect here."
            ),
        })
    elif ctx.vegetation_index < 0.60:
        causes.append({
            "cause": "Limited Green Cover",
            "severity": "Moderate",
            "detail": (
                f"A vegetation index of {ctx.vegetation_index:.2f} provides insufficient "
                "green cover to fully offset the heat generated by the local infrastructure."
            ),
        })

    if ctx.temperature >= 36:
        causes.append({
            "cause": "Extreme Thermal Accumulation",
            "severity": "Critical",
            "detail": (
                f"The current temperature of {ctx.temperature:.1f}°C exceeds safe urban thresholds, "
                f"exposing the {ctx.population_density.lower()}-density population to elevated heat stress."
            ),
        })
    elif ctx.temperature >= 32:
        causes.append({
            "cause": "Above-Average Temperatures",
            "severity": "High",
            "detail": (
                f"The recorded {ctx.temperature:.1f}°C is elevated relative to baseline conditions, "
                "indicating persistent thermal trapping."
            ),
        })

    if ctx.wind_speed < 5:
        causes.append({
            "cause": "Stagnant Airflow",
            "severity": "High",
            "detail": (
                f"A very low wind speed of {ctx.wind_speed:.1f} km/h severely limits convective cooling, "
                "allowing heat to remain trapped within the urban canyons."
            ),
        })
    elif ctx.wind_speed < 8:
        causes.append({
            "cause": "Restricted Ventilation",
            "severity": "Moderate",
            "detail": (
                f"Wind speed of {ctx.wind_speed:.1f} km/h is insufficient to disperse accumulated surface heat quickly."
            ),
        })

    if scores["urbanization_impact_score"] >= 70:
        causes.append({
            "cause": "Aggressive Urbanization",
            "severity": "Critical",
            "detail": (
                f"The {ctx.urban_growth.lower()} rate of development has rapidly replaced permeable natural surfaces "
                f"with heat-absorbing materials, fundamentally altering the microclimate."
            ),
        })

    if not causes:
        causes.append({
            "cause": "Stable Environmental Profile",
            "severity": "Low",
            "detail": (
                "Current indicators show a balanced microclimate with manageable heat retention, "
                f"typical of {ctx.development_stage.lower()} {ctx.area_type.lower()} zones."
            ),
        })

    return causes
